### ISSUE TITLE
Model retraining

### ISSUE THREAD

**Issue by eaedk** [Faizan-E-Mustafa/Image-Captioning#1]
Hi, please i want your help to retrained your model for an other tasks

**Comment by Faizan-E-Mustafa** [comment]
Sorry for the late response . Let me know if i could be of any help now .

**Comment by eaedk** [comment]
No matter, I wanted to know in detail how the model works, to re-train it.

**Comment by Faizan-E-Mustafa** [comment]
Have you read the blog ? i tried to explain model a little bit in detail . if you want detail about some specific component , just let me know 
Blog : https://medium.com/@faizanmustafa75/keras-implementation-of-image-captioning-model-3a7ab68e67d4

**Comment by eaedk** [comment]
The blog ? please send me the link .

**Comment by Faizan-E-Mustafa** [comment]
https://medium.com/@faizanmustafa75/keras-implementation-of-image-captioning-model-3a7ab68e67d4

**Comment by eaedk** [comment]
thanks!

**Comment by Faizan-E-Mustafa** [comment]
Welcome
